### ISSUE TITLE
How to use query_object.query

### ISSUE THREAD

**Issue by lucasdiedrich** [ZBoxApp/zimbra-admin-api-js#14]
Is there anyway that i could use multiple parameter on the query filter?

It says that it is an ldap filter, but i can't manage to work with multiple filters.

Thanks.

**Comment by pbruna** [comment]
Hi @lucasdiedrich do you have an example of the query you want to make?

**Comment by lucasdiedrich** [comment]
Of course, for example, i would like to filter some user who contains "lucas" inside **cn** OR **uid**, using ldap search would be like **(|(cn=*lucas*)(uid=*lucas*))**. 

But i can't figure how to use inside the query because the query is appended to other pre-defined ldap-query, right?

**Comment by pbruna** [comment]
Hi,
You can make any search using `directorySearch(query_object, callback)`, like:

```javascript
var queryObject = {
  query: '(|(cn=*lucas*)(uid=*lucas*))',
  types: 'accounts'
};

client.directorySearch(queryObject, function(e, d){
  if (e) return console.error(e);
  console.log(d);
});
```

`directorySearch()` is documented here: https://github.com/ZBoxApp/zimbra-admin-api-js/blob/master/src/index.js#L637

**Comment by lucasdiedrich** [comment]
@pbruna, very interesting, i will be testing that, i did test using another way that i didn't thought before, and it seems to work.

```javascript	
var query_object = { 
   query: '|(cn=*'+ id +'*)(name=*' + id + ')'
}
client.getAllAccounts(t, function(e, d){
  if (e) return console.error(e);
  console.log(d);
});
```

Anyway, both ways could attend what i need, i think it should mark this as #closed .

Thanks @pbruna

**Comment by pbruna** [comment]
Great!! 👍
